# This is a central config file to store all configuration parameters for RLHPD.

# Example usage:
# from common import utils
# cfg = utils.load_config("config.yaml")
# # Returns a Munch file which is a dictionary-like object that supports
# # attribute-style access (object.attribute.path)
# # See: https://github.com/Infinidat/munch
# print(cfg.out.base_dir)

env_task: MineRLBasaltFindCave-v0
demos_dir: /home/junshern.chan/git/basalt-notyourrl/data

out:
    base_dir: ./output

##########
# DQfD
##########

# DQfD args that are common to both pretraining and training
dqfd_args:
    env_name: MineRLBasaltFindCave-v0
    data_dir: /home/lieberummaas/datadisk/minerl/data #TODO -> change this accordingly
    log_dir: ./output
    num_expert_episodes: 100 # usually less than 100 are available -> takes all episodes
    horizon: 50
    batch_size: 100
    save_freq: 100
    update_freq: 100
    lr: 0.0003
    epsilon: 0.01
    PER_exponent: 0.4
    IS_exponent_0: 0.6
    agent_p_offset:  0.001
    expert_p_offset: 1
    weight_decay: 0.00001
    supervised_loss_margin: 0.8
    discount_factor: 0.99
    pretrain_steps: 100000

# args that are special to pretraining
pretrain_dqfd_args:
    model_path: ./output/MineRLBasaltFindCave-v0/Q_0.pth
    n_hid: 64
    vec_feature_dim: 128
    vec_network_dim: 128
    pov_feature_dim: 128
    q_net_dim: 128

# args that are special to training
train_dqfd_args:
    agent_memory_capacity: 100000 
    train_steps: 100000
    action_repeat: 1
    model_path: ./output/MineRLBasaltFindCave-v0/Q_0.pth
    new_model_path: ./output/MineRLBasaltFindCave-v0/Q_1.pth
    reward_model_path: ./output/MineRLBasaltFindCave-v0/reward_model_0.pth

###########
# Sampling
###########

sampler:
    db_path: ./output/annotation_buffer.db
    traj_dir: ./output/trajectories/
    rnd_seed: 0
    max_traj_length: 10
    num_traj: 5
    num_samples: 5
    sample_length: 5
    pair_per_sample: 2
    autolabel: True
    autolabel_per_sample: 1

###########
# Rating
###########

rate_ui:
    videos_dir: ./output/videos
    video_fps: 20