# This is a central config file to store all configuration parameters for RLHPD.
env_task: MineRLBasaltFindCave-v0
demos_path: ./data
outputs_base: ./output
run_id: null # Autopopulate with timestamp if null
# All paths with `out_` prefix will be relative to $outputs_base/$run_id
out_cfg_file: config.yaml
out_log_dir: log
out_models_dir: models
out_annotation_db: annotation.db
out_replay_buf_file: replay_buf.pkl