wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/rlhpd/DQfD_training.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1633540915
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.6
      5: 0.12.4
      8:
      - 5
